// src/app/weeks-of-month_module/day-of-month.component.tsx
import { Appointment } from '@shared/appointment.type';
import { Component, Input, OnInit } from '@angular/core';
import { DayScheduleService } from '@shared/day-schedule.service';
import { MonthNamesData as monthNames } from '@shared/month-names.data';
import { SelectedData as selected } from '@app/month-and-year-controls_module/selected.data';
import { TodayData as today } from '@shared/today.data';


@Component({
	selector: 'day-of-month',
	template: `
		<div class="calendar-day day-square" [class.today]="isToday()">
			&nbsp;{{number}}&nbsp;

			<span *ngIf="appointments && appointments.length" class="num-appointments">
				{{appointments.length}}
			</span>
		</div>
	`,
	styles: [`.today {background-color: rgba(167, 255, 167, 0.87)}`]
})
export class DayOfMonthComponent implements OnInit {

	@Input() number: '' | number = '';
	appointments: Appointment[] | undefined;


	constructor(private __schedule: DayScheduleService) {}


	async ngOnInit() { // @ts-ignore
		this.appointments = await this.__schedule.get(
			selected.year, this.__getMonthNumber(selected.month), Number(this.number)
		);
	}


	isToday(): boolean {
		return (
			today.data.day === this.number &&
			monthNames.data[today.data.monthIndex] === selected.month  &&
			today.data.year === selected.year
		);
	}


	private __getMonthNumber(monthName) {
		return monthNames.data.indexOf(monthName) + 1;
	}

}

// src/app/weeks-of-month_module/DayOfMonth.component.tsx
import { MonthNamesData as monthNames } from '@writetome51/calendar-helpers';
import { SelectedData as selected } from '@writetome51/calendar-helpers';
import { TodayData as today } from '@writetome51/calendar-helpers';
import React from 'react';
import { DayScheduleService } from '../shared/day-schedule.service';
import { Appointment } from '../shared/appointment.type';


export class DayOfMonth extends React.Component<any, any>{

	appointments: Appointment[] | undefined;


	constructor(private __schedule: DayScheduleService) {
		// @ts-ignore
		super(props);
	}


	async ngOnInit() { // @ts-ignore
		this.appointments = await this.__schedule.get(
			selected.year, this.__getMonthNumber(selected.month), Number(this.props.number)
		);
	}


	render() {
		return (
			<div className="calendar-day day-square {this.isToday() ? today : ''}">
				&nbsp;{this.props.number}&nbsp;

				{this.appointments && this.appointments.length ? this.renderNumAppointments(): ''}
			</div>
		);
	}


	renderNumAppointments(){
		return (
			<span className="num-appointments">
				{ // @ts-ignore
					this.appointments.length
				}
			</span>
		);
	}


	isToday(): boolean {
		return (
			today.data.day === this.props.number &&
			monthNames.data[today.data.monthIndex] === selected.month  &&
			today.data.year === selected.year
		);
	}


	private __getMonthNumber(monthName: string) {
		return monthNames.data.indexOf(monthName) + 1;
	}

}
