// src/app/WeeksOfMonth_component/WeeksOfMonth.component.tsx
import { DaysOfMonth } from '@writetome51/calendar-helpers';
import { getArrFilled } from '@writetome51/get-arr-filled';
import { getPage } from '@writetome51/array-get-page';
import { getRoundedUp } from '@writetome51/get-rounded-up-down';
import React from 'react';
import { DayOfMonth } from './DayOfMonth.component';


export class WeeksOfMonth extends React.Component {

	weeks: DaysOfMonth[] = [];
	props: { days: DaysOfMonth | undefined } = {days: undefined};


	render() {
		this.__prepareToRender();
		return this.weeks.map((week) => this.__renderWeek(week));
	}


	private __prepareToRender() {
		if (this.props.days) this.weeks = this.__getSplitIntoWeeks(this.props.days);
	}


	private __renderWeek(week: any[]) {
		return (
			<div className="week-block">
				{week.map((day: number) => this.__renderDay(day))}
			</div>
		);
	}


	private __renderDay(day: number) {
		return (
			<div className="day-column">
				<DayOfMonth number={day}/>
			</div>
		);
	}


	private __getSplitIntoWeeks(days: DaysOfMonth) {
		let weeks = getArrFilled(
			getRoundedUp(days.length / 7),
			// @ts-ignore
			(i) => getPage(i + 1, 7, days)
		);
		let last = weeks.length - 1;
		weeks[last].push(...this.__getFillerForLastWeek(last));
		return weeks;
	}


	private __getFillerForLastWeek(lastWeekIndex: number): ''[] {
		let lastLen = this.weeks[lastWeekIndex].length;
		if (lastLen < 7) return getArrFilled(7 - lastLen, () => '');
		else return [];
	}

}

// src/app/weeks-of-month_module/weeks-of-month.component.ts
import { Component, Input } from '@angular/core';
import { DaysOfMonth } from '@writetome51/calendar-helpers';
import { getArrFilled } from '@writetome51/get-arr-filled';
import { getPage } from '@writetome51/array-get-page';
import { getRoundedUp } from '@writetome51/get-rounded-up-down';


@Component({
	selector: 'weeks-of-month',
	template: `
		<div *ngFor="let week of weeks" class="week-block">
			<div *ngFor="let day of week" class="day-column">
				<day-of-month [number]="day"></day-of-month>
			</div>
		</div>
	`
})
export class WeeksOfMonthComponent {


	@Input() set days(dys: DaysOfMonth) {
		this.weeks = getArrFilled(
			getRoundedUp(dys.length / 7),
			// @ts-ignore
			(i) => getPage(i + 1, 7, dys)
		);
		let last = this.weeks.length -1;
		this.weeks[last].push(...this.__getFillerForLastWeek(last));
	}


	weeks: DaysOfMonth[] = [];


	private __getFillerForLastWeek(lastWeekIndex): ''[] {
		let lastLen = this.weeks[lastWeekIndex].length;
		if (lastLen < 7) return getArrFilled(7 - lastLen, () => '');
		else return [];
	}

}
