// src/app/month-and-year-controls_module/month-controls_module/selected-month.component.ts
import { Component } from '@angular/core';
import { MonthDisplayService } from '@writetome51/calendar-helpers';
import { MonthNamesData } from '@writetome51/calendar-helpers';
import { SelectedData } from '@writetome51/calendar-helpers';


@Component({
	selector: 'selected-month',
	template: `
		<div id="month-name" class="calendar-input-container">
			<mat-form-field appearance="outline" class="fills-parent-height">

				<mat-select id="month-selector" class="fills-parent-dimensions"
							[(value)]="selected.month" [placeholder]="selected.month"
							(valueChange)="monthDisplay.updateOnChangeOfSelectedMonthOrYear()"
				>
					<mat-option *ngFor="let monthName of monthNames.data" [value]="monthName">
						{{monthName}}
					</mat-option>
				</mat-select>

			</mat-form-field>
		</div>
	`,
	styles: [
		`#month-name {
			display: inline-block;
		}`,
		`mat-form-field {
			width: 140px;
			padding: 0;
		}`,
		`#month-selector {
			padding-left: 4px;
		}`
	]
})
export class SelectedMonthComponent {

	selected = SelectedData;
	monthNames = MonthNamesData;
	monthDisplay = MonthDisplayService;

}

// src/app/MonthAndYearControls_component/MonthControls_component/SelectedMonth.component.tsx
import { MonthDisplayService, MonthNamesData, SelectedData } from '@writetome51/calendar-helpers';
import React from 'react';
import { MonthOptions } from './MonthOptions.component';
import { MDCSelect } from '@material/select';


export class SelectedMonth extends React.Component {

	// @ts-ignore
	mdcSelect: MDCSelect;
	selected = SelectedData;
	monthNames = MonthNamesData;
	monthDisplay = MonthDisplayService;


	render() {
		return (
			<div id="month-selector" className="fills-parent-dimensions"
				 style={{paddingLeft: '4px'}}
			>
				{this.__initialize_mdcSelect()}
				<MonthOptions/>

			</div>
		);
	}


	private __initialize_mdcSelect() {
		// @ts-ignore
		this.mdcSelect = new MDCSelect(document.getElementById('month-selector'));
		this.mdcSelect.value = this.selected.month;
		this.mdcSelect.listen('MDCSelect:change', () => {
			this.monthDisplay.updateOnChangeOfSelectedMonthOrYear();
			this.mdcSelect.value = this.selected.month;
		});
	}

}
