// src/app/DayNames.component.tsx
import React from 'react';


export class DayNames extends React.Component {

	readonly data = ['Sun', 'Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat'];


	render() {
		return (
			<div className="week-block">
				{this.data.map((name) => this.renderDayName(name))}
			</div>
		);
	}


	renderDayName(name: string) {
		return (
			<div className="day-column" style={{border: '1px solid transparent'}}>
				<div className="calendar-day day-name">{name}</div>
			</div>
		);
	}

}

// src/app/day-names.component.ts
import { Component } from '@angular/core';


@Component({
	selector: 'day-names',
	template: `
		<div class="week-block">
			<div class="day-column" *ngFor="let dayName of data">
				<div class="calendar-day day-name">{{dayName}}</div>
			</div>
		</div>
	`,
	styles:[`.day-column {border: 1px solid transparent;}`]
})
export class DayNamesComponent {

	readonly data = ['Sun', 'Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat'];

}
