// src/app/MonthAndYearControls_component/MonthAndYearControls.component.tsx
import { MonthControls } from './MonthControls_component/MonthControls.component';
import { YearControls } from './YearControls_component/YearControls.component';


export function MonthAndYearControls() {
	return (
		<div id="month-and-year-controls" style={{display: 'flex', justifyContent: 'center'}}>
			<MonthControls/>
			<YearControls/>
		</div>
	);
}

// src/app/month-and-year-controls_module/month-and-year-controls.component.ts
import { Component } from '@angular/core';


@Component({
	selector: 'month-and-year-controls',
	template: `
		<div id="month-and-year-controls">
			<month-controls></month-controls>
			<year-controls></year-controls>
		</div>
	`,
	styles: [
		`#month-and-year-controls {
			display: flex;
			justify-content: center;
		}`
	]
})
export class MonthAndYearControlsComponent {}
