// src/app/MonthAndYearControls_component/YearControls_component/ForwardOneYearButton.component.tsx
import { MonthDisplayService as monthDisplay, SelectedData } from '@writetome51/calendar-helpers';
import React from 'react';
import { RapidRepeatMatIconButton } from '../../shared/RapidRepeatMatIconButton.component';
import { ClickExecuteRapidRepeatFunctionContext }
	from '../../shared/ClickExecuteRapidRepeatFunction_component/click-execute-rapid-repeat-function-context.interface';


export class ForwardOneYearButton extends React.Component
	implements ClickExecuteRapidRepeatFunctionContext {

	props: { [prop: string]: any } = {};
	selected = SelectedData;


	render() {
		return (
			<RapidRepeatMatIconButton matIcon="keyboard_arrow_right" id="forward-one-year"
				aria-label="add one year"
			/>
		);
	}


	function() {
		++this.selected.year;
		monthDisplay.updateOnChangeOfSelectedMonthOrYear();
	}

}

// src/app/month-and-year-controls_module/YearControls_component/forward-one-year-button.component.tsx
import { Component } from '@angular/core';
import { MonthDisplayService as monthDisplay } from '@writetome51/calendar-helpers';
import { SelectedData } from '@writetome51/calendar-helpers';
import { ClickExecuteRapidRepeatFunctionContext }
	from '@shared/ClickExecuteRapidRepeatFunction_component/click-execute-rapid-repeat-function-context.interface';


@Component({
	selector: 'forward-one-year-button',
	template: `
		<rapid-repeat-mat-icon-button [context]="this" aria-label="add one year"
			id="forward-one-year"
		>
			keyboard_arrow_right
		</rapid-repeat-mat-icon-button>
	`
})
export class ForwardOneYearButtonComponent implements ClickExecuteRapidRepeatFunctionContext {

	selected = SelectedData;


	function() {
		++this.selected.year;
		monthDisplay.updateOnChangeOfSelectedMonthOrYear();
	}

}
