// src/app/month-and-year-controls_module/year-controls_module/year-controls.component.ts
import { Component } from '@angular/core';


@Component({
	selector: 'year-controls',
	template: `
		<div id="year-controls" class="controls-container">

			<selected-year></selected-year>

			<div class="left-and-right-arrow-buttons-container">
				<back-one-year-button class="control-button"></back-one-year-button>
				<forward-one-year-button class="control-button"></forward-one-year-button>
			</div>
		</div>
	`,
	styles: [
		`.left-and-right-arrow-buttons-container{
			margin-left: 5px;
			height:100%;
		}`
	]
})
export class YearControlsComponent {}

// src/app/month-and-year-controls_module/YearControls_component/YearControls.component.tsx
import React from 'react';


export class YearControls extends React.Component {

	render() {
		return (
			<div id="year-controls" className="controls-container">

				<selected-year></selected-year>

				<div className="left-and-right-arrow-buttons-container"
					 style={{marginLeft:'5px', height:'100%'}}
				>
					<back-one-year-button className="control-button"></back-one-year-button>
					<forward-one-year-button className="control-button"></forward-one-year-button>
				</div>
			</div>
		);
	}
}
