// src/app/month-and-year-controls_module/YearControls_component/ForwardOneYearButton.component.tsx
import { MonthDisplayService as monthDisplay, SelectedData } from '@writetome51/calendar-helpers';
import React from 'react';
import { RapidRepeatMatIconButton } from '../../shared/RapidRepeatMatIconButton.component';
import { ClickExecuteRapidRepeatFunctionContext }
	from '../../shared/ClickExecuteRapidRepeatFunction_component/click-execute-rapid-repeat-function-context.interface';


export class ForwardOneYearButton extends React.Component
	implements ClickExecuteRapidRepeatFunctionContext {

	selected = SelectedData;


	render() {
		return (
			<RapidRepeatMatIconButton context={this} aria-label="add one year"
									  id="forward-one-year"
			>
				keyboard_arrow_right
			</RapidRepeatMatIconButton>
		);
	}


	function() {
		++this.selected.year;
		monthDisplay.updateOnChangeOfSelectedMonthOrYear();
	}

}

// src/app/month-and-year-controls_module/year-controls_module/forward-one-year-button.component.tsx
import { Component } from '@angular/core';
import { MonthDisplayService } from '../month-display_service/month-display.service';
import { SelectedData } from '../selected.data';
import { ClickExecuteRapidRepeatFunctionContext }
	from '@shared/click-execute-rapid-repeat-function_module/click-execute-rapid-repeat-function-context.interface';


@Component({
	selector: 'forward-one-year-button',
	template: `
		<rapid-repeat-mat-icon-button [context]="this" aria-label="add one year"
			id="forward-one-year"
		>
			keyboard_arrow_right
		</rapid-repeat-mat-icon-button>
	`
})
export class ForwardOneYearButtonComponent implements ClickExecuteRapidRepeatFunctionContext {

	selected = SelectedData;

	constructor(public monthDisplay: MonthDisplayService) {}


	function() {
		++this.selected.year;
		this.monthDisplay.updateOnChangeOfSelectedMonthOrYear();
	}

}
