// src/app/month-and-year-controls_module/YearControls_component/SelectedYear.component.tsx
import { SelectedData } from '@writetome51/calendar-helpers';
import React from 'react';


export class SelectedYear extends React.Component {

	selected = SelectedData;


	render() {
		return (
			<div id="year-container" className="calendar-input-container"
				 style={{paddingLeft: '8px', top: '30px'}}
			>
				{this.selected.year}
			</div>
		);
	}

}

// src/app/month-and-year-controls_module/year-controls_module/selected-year.component.tsx
import { Component } from '@angular/core';
import { SelectedData } from '../selected.data';


@Component({
	selector: 'selected-year',
	template: `
		<div id="year-container" class="calendar-input-container">
			{{selected.year}}
		</div>
	`,
	styles: [
		`#year-container {
			padding-left: 8px;
			top: 30px;
		}`
	]
})
export class SelectedYearComponent {

	selected = SelectedData;

}
